apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: wordpress
  name: wp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wordpress
    spec:
      containers:
        - env:
          - name: WORDPRESS_DB_HOST
            valueFrom:
              secretKeyRef:
                name: wp-secret
                key: HOST
          - name: WORDPRESS_DB_USER
            valueFrom:
              secretKeyRef:
                name: wp-secret
                key: USER
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: wp-secret
                key: PASSWORD
          - name: WORDPRESS_DB_NAME
            valueFrom:
              secretKeyRef:
                name: wp-secret
                key: DATABASE
          image: wordpress:5.2
          name: wordpress
          ports:
          - containerPort: 80

          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html
      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: pvc-wordpress

status: {}

