apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-job
spec:
  schedule: "*/1 * * * *"  # Run every minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron-container
            image: alpine
            command: ["echo", "Hello from cron job"]
          restartPolicy: OnFailure

