apiVersion: batch/v1
kind: Job
metadata:
  name: parallel-job
spec:
  parallelism: 3
  completions: 6
  template:
    spec:
      containers:
      - name: parallel-container
        image: ubuntu
        command: ["echo", "Hello from Kubernetes parallel job"]
      restartPolicy: Never

